<?php
/**
 * Custom tab template
 */
?>

<div class="grid"/>

<?php
$collection = Mage::getModel('palorus/insight')->getCollection();
if ($collection->count() >= 1) {
    // store the retrieved feeds
    $purchases = array();
    // iterate over the retrieved retrieved collection
    foreach ($collection as $purchase) {
        $purchases[] = $purchase->getData();
    }
}
?>

<?php echo $this->getUrl('*/sales_order/view/order_id/206') ?>
<table cellspacing="0" class="data">
            <thead>
                <tr class="headings">
		    <th>Order Id</th>
                    <th>Last 4</th>
                    <th>Affluence</th>
                    <th>prepaid</th>
                    <th>reloadable</th>
                    <th>available_balance</th>
                    <th>issuing_country</th>
                </tr>
            </thead>
            

         
        <?php $i = 1; ?>
        <?php foreach($purchases as $purchase) { ?>
		<tr titl>
			<td id="OrderId_<?php echo $i;?>"><?php echo $purchase['order_id']; ?></td>
			<td id="Last4_<?php echo $i;?>"><?php echo $purchase['last']; ?></td>
			<td id="Affluence_<?php echo $i;?>"><?php echo $purchase['affluence']; ?></td>
			<td id="Prepaid_<?php echo $i;?>"><?php echo $purchase['prepaid']; ?></td>
			<td id="Reloadable_<?php echo $i;?>"><?php echo $purchase['reloadable']; ?></td>
			<td id="AvailableBalance_<?php echo $i;?>"><?php echo $purchase['available_balance']; ?></td>
			<td id="IssuingCountry_<?php echo $i;?>"><?php echo $purchase['issuing_country']; ?></td>
		</tr>
		<?php $i++; ?> 
		<?php } ?>


</table>
</div>
