<fieldset class="form-list">
    <?php 
    $_code=$this->getMethodCode(); 
    $companyname_enable = Mage::getModel('Litle_LEcheck_Model_PaymentLogic')->getConfigData("companyname_enable");
    $user_logged_in = Mage::getSingleton('customer/session')->isLoggedIn();
    ?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_echeck_routing_number" class="required"><?php echo $this->__('Bank routing number') ?><em>*</em></label><br />
                <input id="<?php echo $_code ?>_echeck_routing_number" name="payment[echeck_routing_number]" class="input-text required-entry">
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_echeck_bank_acct_num" class="required"><?php echo $this->__('Bank account number') ?><em>*</em></label><br />
                <input id="<?php echo $_code ?>_echeck_bank_acct_num" name="payment[echeck_bank_acct_num]" class="input-text required-entry">
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_echeck_account_type" class="required"><?php echo $this->__('Account type') ?><em>*</em></label><br />
                <select id="<?php echo $_code ?>_echeck_account_type" name="payment[echeck_account_type]" class="input-text required-entry">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_accountType = $this->getInfoData('account_type') ?>
                <?php foreach ($this->getAccountAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_accountType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
        <?php if ($companyname_enable): ?>
            <?php 
              $company_name = "";
              if ($user_logged_in) {
                $customer = Mage::getSingleton('customer/session')->getCustomer();

                $address_id = $customer->getDefaultBilling();
                if ((int)$address_id) {
                    $address = Mage::getModel('customer/address')->load($address_id);
                    $company_name = $address->getCompany();
                }
              }
              ?>
            <li>
             <div class="input-box">
                <label for="<?php echo $_code ?>_echeck_company_name" class="required"><?php echo $this->__('Company Name') ?><em>*</em></label><br />
                <input id="<?php echo $_code ?>_echeck_company_name" name="payment[echeck_company_name]" value="<?php echo $company_name ?>" title="<?php echo $this->__('Company') ?>" class="input-text required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" >
            </div>   
            </li>
        <?php endif;?>
        <!-- li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_echeck_type"><?php echo $this->__('Echeck type') ?> <span class="required">*</span></label><br />
                <input id="<?php echo $_code ?>_echeck_type" name="payment[echeck_type]" class="required-entry">
            </div>
        </li-->
    </ul>
</fieldset>
